export const AUTH_SUCCEEDED = 'AUTH_SUCCEEDED'
export const ERR_MSG = 'ERR_MSG'
export const UPDATE_USER = 'UPDATE_USER'
export const RESET_USER = 'RESET_USER'
export const RECEIVE_USER_LIST = 'RECEIVE_USER_LIST'
export const RECEIVE_MSG_LIST = 'RECEIVE_MSG_LIST'
export const RECEIVE_MSG = 'RECEIVE_MSG'
export const MARK_AS_READ = 'MARK_AS_READ'